schema_version = "0.0.1"

id = "meddle_tools"
version = "0.0.24"
name = "Meddle Tools"
tagline = "This is another extension"
maintainer = "PassiveModding"
type = "add-on"
website = "https://github.com/PassiveModding/MeddleTools"

tags = ["Material"]

blender_version_min = "4.2.0"

license = [
  "SPDX:AGPL-3.0-or-later",
]

[permissions]
files = "Import files from meddle cache directory"